var dir_89b676f209c15f876da8182db9fde96b =
[
    [ "furi_hal.h", "furi__hal_8h.html", "furi__hal_8h" ],
    [ "furi_hal_bt.h", "furi__hal__bt_8h.html", "furi__hal__bt_8h" ],
    [ "furi_hal_bt_hid.h", "furi__hal__bt__hid_8h_source.html", null ],
    [ "furi_hal_bt_serial.h", "furi__hal__bt__serial_8h_source.html", null ],
    [ "furi_hal_compress.h", "furi__hal__compress_8h.html", "furi__hal__compress_8h" ],
    [ "furi_hal_cortex.h", "furi__hal__cortex_8h.html", "furi__hal__cortex_8h" ],
    [ "furi_hal_crypto.h", "furi__hal__crypto_8h.html", "furi__hal__crypto_8h" ],
    [ "furi_hal_debug.h", "furi__hal__debug_8h.html", "furi__hal__debug_8h" ],
    [ "furi_hal_i2c.h", "furi__hal__i2c_8h.html", "furi__hal__i2c_8h" ],
    [ "furi_hal_ibutton.h", "furi__hal__ibutton_8h.html", "furi__hal__ibutton_8h" ],
    [ "furi_hal_info.h", "furi__hal__info_8h.html", "furi__hal__info_8h" ],
    [ "furi_hal_infrared.h", "furi__hal__infrared_8h.html", "furi__hal__infrared_8h" ],
    [ "furi_hal_light.h", "furi__hal__light_8h.html", "furi__hal__light_8h" ],
    [ "furi_hal_memory.h", "furi__hal__memory_8h.html", "furi__hal__memory_8h" ],
    [ "furi_hal_mpu.h", "furi__hal__mpu_8h_source.html", null ],
    [ "furi_hal_nfc.h", "furi__hal__nfc_8h.html", "furi__hal__nfc_8h" ],
    [ "furi_hal_power.h", "furi__hal__power_8h.html", "furi__hal__power_8h" ],
    [ "furi_hal_random.h", "furi__hal__random_8h_source.html", null ],
    [ "furi_hal_region.h", "furi__hal__region_8h_source.html", null ],
    [ "furi_hal_rfid.h", "furi__hal__rfid_8h.html", "furi__hal__rfid_8h" ],
    [ "furi_hal_rtc.h", "furi__hal__rtc_8h.html", "furi__hal__rtc_8h" ],
    [ "furi_hal_sd.h", "furi__hal__sd_8h.html", "furi__hal__sd_8h" ],
    [ "furi_hal_speaker.h", "furi__hal__speaker_8h.html", "furi__hal__speaker_8h" ],
    [ "furi_hal_spi.h", "furi__hal__spi_8h_source.html", null ],
    [ "furi_hal_subghz.h", "furi__hal__subghz_8h.html", "furi__hal__subghz_8h" ],
    [ "furi_hal_usb.h", "furi__hal__usb_8h_source.html", null ],
    [ "furi_hal_usb_hid.h", "furi__hal__usb__hid_8h_source.html", null ],
    [ "furi_hal_usb_hid_u2f.h", "furi__hal__usb__hid__u2f_8h_source.html", null ],
    [ "furi_hal_version.h", "furi__hal__version_8h.html", "furi__hal__version_8h" ],
    [ "furi_hal_vibro.h", "furi__hal__vibro_8h.html", "furi__hal__vibro_8h" ]
];