name: 'Generate documentation with Doxygen'

on:
  push:
    branches:
      - dev

env:
  TARGETS: f7
  DEFAULT_TARGET: f7

jobs:
  doxygen:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Wipe workspace'
        run: find ./ -mount -maxdepth 1 -exec rm -rf {} \;

      - name: 'Checkout code'
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Get commit details'
        id: names
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            TYPE="pull"
          elif [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            TYPE="tag"
          else
            TYPE="other"
          fi
          python3 scripts/get_env.py "--event_file=${{ github.event_path }}" "--type=$TYPE"

      - name: 'Generate documentation'
        uses: mattnotmitt/doxygen-action@v1.9.8
        with:
          working-directory: 'documentation/'
          doxyfile-path: './doxygen/Doxyfile-awesome.cfg'

      - name: 'Upload documentation'
        uses: jakejarvis/s3-sync-action@v0.5.1
        env:
          AWS_S3_BUCKET: "${{ secrets.FW_DOCS_AWS_BUCKET }}"
          AWS_ACCESS_KEY_ID: "${{ secrets.FW_DOCS_AWS_ACCESS_KEY }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.FW_DOCS_AWS_SECRET_KEY }}"
          AWS_REGION: "${{ secrets.FW_DOCS_AWS_REGION }}"
          SOURCE_DIR: "./documentation/doxygen/build/html"
          DEST_DIR: "${{steps.names.outputs.branch_name}}"
        with:
          args: "--delete"

